# -*- coding: utf-8 -*-
"""Практика1_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_8cw6G6d1uaLrTqSDoWUE_HUlcPApnBJ
"""

import re

def read_file(file_name):

  pattern1 = re.compile(r'[?!\n.,]+')
  pattern2 = re.compile(r'\s+') #to get rid of double spaces

  with open(file_name) as file:

    result = [pattern2.sub(" ",
                           pattern1.sub('', line))
                              .replace("'s", " is")
                              .replace("'m", " am")
                              .replace("'re", " are")
                                .lower()
                                .split(sep=' ') for line in file]

  return result

# reading file
df = read_file('first_task.txt')

# make list out of list of lists
df_flat = [el for line in df for el in line]

# count frequencies
res = {key: df_flat.count(key) for key in df_flat}

# sort dict by freq
res2 = {k: v for k, v in sorted(res.items(), key=lambda item: item[1], reverse=True)}

def write_file(file_name, dictionary):

  with open(file_name, 'w') as file:
          for key in dictionary:
              file.write(f'{key}:{dictionary[key]}\n')

# write sorted dict into file
write_file('first_task_output1.txt', res2)

"""Варианты 2, 12, 22, …
Подсчитайте количество, а также долю всех слов, начинающихся на согласную букву в тексте.

"""

consonants = 'qwrtpsdfghjklzxcvbnm'
words_cons = [word for word in df_flat if word[0] in consonants]

with open('first_task_output2.txt', 'w') as file:
  file.write(str(len(words_cons)) + '\n' + str(round(len(words_cons)/len(df_flat),2)))