# -*- coding: utf-8 -*-
"""Практика1_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yl3zaXmxGZUo186x7aeaHW0TX4-qSaqW
"""

import numpy as np

# function to transform numbers as str d.t. into float d.t.
# and to replace 'N/A' by numpy nan
def na_handler(el):
  try:
    return float(el)
  except:
    if el == 'N/A':
      return np.nan

def read_file(file_name):

  with open(file_name) as file:

    return [list(map(na_handler, #to replace N/A by np.nan
                       line.replace("\n", "").split(sep=' '))) for line in file]

df = read_file('second_task.txt')

"""Варианты 2, 12, 22, …  
Операция в рамках одной строки: суммирование только абсолютных значений отрицательных чисел.  
Операция для полученного столбца: вывод столбца, а также расчет его среднего арифметического значения.

"""

# calculate sum of every row
sum_by_row = [sum([abs(el) for el in line if el < 0]) for line in df]

with open('second_task_output.txt', 'w') as file:

  for num in sum_by_row:
    file.write(str(num) + '\n')

  file.write('\n' + str(round(np.mean(sum_by_row),2)))