# -*- coding: utf-8 -*-
"""Практика1_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o7e0Gi5vEsu8HqaQICCfO_G3dPkELYQf
"""

import numpy as np

# function to transform numbers as str d.t. into float d.t.
# and to replace 'N/A' by numpy nan
def na_handler(el):
  try:
    return float(el)
  except:
    if el == 'N/A':
      return np.nan

def read_file(file_name):

  with open(file_name) as file:

    return [list(map(na_handler, #to replace N/A by np.nan
                       line.replace("\n", "").split(sep=' '))) for line in file]

df = read_file('third_task.txt')

# replace NaN values with mean of nearby elements
for line in df:
  for el in range(0,len(line)-1):
    if np.isnan(line[el]):
      line[el] = (line[el-1] + line[el+1])/2

"""Варианты 2, 12, 22, …  
Условие фильтрации - Оставляем только четные значения, превышающие 500  
Формат вывода - Сумма по каждой строке
"""

sum_by_row = [sum([el for el in line if el > 500 and el % 2 == 0]) for line in df]

with open('third_task_output.txt', 'w') as file:

  for num in sum_by_row:
    file.write(str(num) + '\n')