# -*- coding: utf-8 -*-
"""Практика1_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wKGh2K6aDEBnW7DV3GTLp_wIy9Lg_48t

Считайте csv файл и выполните с ним определенные действия согласно вашему варианту. Результаты поиска значений (среднее, максимум и минимум) запишите в отдельный файл: каждое число на новой строке. Результаты модификаций исходного файла – в отдельный csv файл.

Вариант 42
1. Удалите из таблицы столбец expiration_date
2. Найдите среднее арифметическое по столбцу quantity
3. Найдите максимум по столбцу price
4. Найдите минимум по столбцу quantity
5. Отфильтруйте значения, взяв только те, status которых не равен Awaiting Payment
"""

import pandas as pd

df = pd.read_csv('fourth_task.txt', sep=',')

df.head(5)

# Удалите из таблицы столбец expiration_date
df_dropped = df.drop(['expiration_date'], axis=1)

# Найдите среднее арифметическое по столбцу quantity
mean_quantity = df_dropped['quantity'].mean()

# Найдите максимум по столбцу price
max_price = df_dropped['price'].max()

# Найдите минимум по столбцу quantity
min_quantity = df_dropped['quantity'].min()

# Отфильтруйте значения, взяв только те, status которых не равен Awaiting Payment
df_noawaiting = df_dropped[df_dropped['status'] != 'Awaiting Payment'].reset_index()

# Результаты поиска значений (среднее, максимум и минимум) запишите в отдельный файл: каждое число на новой строке
with open('fourth_task_output1.txt', 'w') as file:

    file.write(str(mean_quantity) + '\n' + str(max_price) + '\n' + str(min_quantity))

# Результаты модификаций исходного файла – в отдельный csv файл.
df_noawaiting.to_csv('fourth_task_output2.csv', encoding='utf-8-sig', index=False)