# -*- coding: utf-8 -*-
"""Практика1_6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ib7OkFT1PswSgWLlbjbhraIlH6GrZhbB

В задании происходит парсинг Disney API (docs: https://disneyapi.dev/)  
Первый этап: спарсить названия фильмов со случайной страницы их списка  
Второй этап: спарсить всех героев случайно выбранного фильма с этой страницы
"""

# импорт библиотек
import requests
import json
import random
import pandas as pd
import numpy as np

# парсинг списка фильмов
# формируем url запроса
url1 = f'http://api.disneyapi.dev/character?page={random.randint(1, 149)}&pageSize=50'

# посылаем запрос
req = requests.get(url1)
print(f'Статус ответа на первый запрос: {req.status_code}')

# из json'а парсим названия фильмов
films = [el['films'] for el in req.json()['data']]

# обрабатываем вложенность списков (когда герой присутствует в нескольких фильмах)
# и берем уникальные значения
films_unique = list(set([x for xs in tmp for x in xs]))

# парсинг песронажей фильма
# формируем url запроса
film = random.choice(films_unique)
print(f'Выбран фильм "{film}"\n')
url2 = f'https://api.disneyapi.dev/character?films={film}'

# посылаем запрос
req2 = requests.get(url2)
print(f'Статус ответа на второй запрос: {req2.status_code}')

# функция на случай, если будут пропуски в данных
def parse(where, what):
  try:
    return where[what]
  except:
    return np.nan

# из json'а парсим информацию и записываем в таблицу формата DataFrame
characters = pd.DataFrame({
    'film': [film for i in range(len(req2.json()['data']))],
    'id': [parse(el, '_id') for el in req2.json()['data']],
    'name': [parse(el, 'name') for el in req2.json()['data']],
    'createdAt': [parse(el, 'createdAt') for el in req2.json()['data']],
    'updatedAt': [parse(el, 'updatedAt') for el in req2.json()['data']],
    'fandom_url': [parse(el, 'sourceUrl') for el in req2.json()['data']],
    'img': [parse(el, 'imageUrl') for el in req2.json()['data']]
})

# предпросмотр датафрейма
characters.head()

characters.to_html('sixth_task_output.html', index=False)