# -*- coding: utf-8 -*-
"""Практика1_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uKtiToiLHZ4e3N5pjKR-PmHBElsc3a33
"""

import pandas as pd

df = pd.read_html('fifth_task.html', encoding='utf-8')

df[0].head()

df[0].to_csv('fifth_task_output.csv', encoding='utf-8-sig')

